### ISSUE TITLE
Input data

### ISSUE THREAD

**Issue by qlootens** [ronenno1/chap#1]
Dear

I'd like to use this algorithm to clean data from a Tobii Eye Tracker. 

The data I received from my faculty contains +- 350k lines with following columns:

`Subject | Session | ID | TETTime | RTTime | CursorX | CursorY | TimestampSec | TimestampMicrosec | XGazePosLeftEye | YGazePosLeftEye | XCameraPosLeftEye | YCameraPosLeftEye | DiameterPupilLeftEye | DistanceLeftEye | ValidityLeftEye | XGazePosRightEye | YGazePosRightEye | XCameraPosRightEye | YCameraPosRightEye | DiameterPupilRightEye | DistanceRightEye | ValidityRightEye | TrialId | AOI | AOIStimulus | CRESP | RESP | ACC | RT | Condition | Cue | Probe | CorrectResponse | TrialName | CurrentObject`

There are 100 trialid's but there are a lot of lines as you see.

How can I manage these data for your algorithm?

Thank you for taking your time to review this comment.

Sincerely,
Quinten Lootens
(Master Computer Science Student @ Ugent

**Comment by ronenno1** [comment]
Solved :)
