### ISSUE TITLE
Group analysis

### ISSUE THREAD

**Issue by marni-23** [ronenno1/chap#5]
Hello,

I am in the process of using CHAP to analyse pupil data taken from EyeLink. I am able to read-in the files and carry out separate analyses, however, I am unable to carry out group analysis. Specifically, when I try click on the group analysis button, I am unable to load the files and the following message appears ‘Error: files not found”. The files are however visible in the folder. Any help with this would be really appreciated.

Also, each trial of my experiment is 10 seconds long and I would like to retrieve the pupil size for specific timeframes within each trial (i.e., 0-3000ms, 4000-7000ms). Is it possible to do this via selecting specific times in the trial onset/offsets? I am unable to put in a custom timeframe in this section of the Advanced Processing Options and Time-Course Visualization gui. 

Many thanks in advance,
Marni

**Comment by ronenno1** [comment]
Dear Marni,
Specific time-windows could be achieved easily by using events.
It means that you need to choose 2 events - one for the onset of the time window, and another one for the offset of the time window. 
These steps should be done for each time-window separately.


Ronen
